Theater/MvcInternetApplication/Controllers/HomeController.cs
using MvcInternetApplication.Controllers.Filters;
using MvcInternetApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcInternetApplication.Controllers
{
    [Culture]
    public class HomeController : Controller
    {
        private TheaterContext db = new TheaterContext();
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize] // Запрещены анонимные обращения к данной странице
        public ActionResult Cabinet()
        {
            string name = User.Identity.Name;
            List<UserPaidShow> users = new List<UserPaidShow>();
            var user = from s in db.UserPaid
                       from s1 in db.UserProfiles
                       from s2 in db.Seats
                       from s3 in db.Performances
                       where s1.UserName == name && s1.UserId == s.UserProfileId && s.PerformanceId == s3.Id && s2.SeatId == s.SeatId
                       select new
                       {
                           s.UserPaidId,
                           s.Payment,
                           s2.SeatId,
                           s3.Name,
                           s3.Date,
                       };
            foreach (var t in user)
            {
                UserPaidShow use = new UserPaidShow();
                use.UserPaidId = t.UserPaidId;
                use.Name = name;
                use.Performance = t.Name;
                use.Date = t.Date;
                use.SeatId = t.SeatId;
                use.Payment = t.Payment;
                users.Add(use);
            }
            ViewBag.User = users;
            return View();
        }

        [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult AdminPanel()
        {
            return View(db.Performances.ToList());
        }

        [Authorize(Roles = "Admin, Сourier")] // К данному методу действия могут получать доступ только пользователи с ролью Admin и Moderator
        public ActionResult Сourier()
        {
            ViewBag.Message = "Курьер";
            return View();
        }

        public ActionResult ChangeCulture(string lang)
        {
            string returnUrl = Request.UrlReferrer.AbsolutePath;
            // Список культур
            List<string> cultures = new List<string>() { "ru", "en", "zh-hk" };
            if (!cultures.Contains(lang))
            {
                lang = "ru";
            }
            // Сохраняем выбранную культуру в куки
            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;   // если куки уже установлено, то обновляем значение
            else
            {

                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(returnUrl);
        }

    }
}

Theater/MvcInternetApplication/Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcInternetApplication.Models;
using MvcInternetApplication.Controllers.Filters;

namespace MvcInternetApplication.Controllers
{
    [Culture]
    public class PerformancesController : Controller
    {
        private TheaterContext db = new TheaterContext();

        //
        // GET: /Default1/

        public ActionResult Index()
        {
            return View(db.Performances.ToList());
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            Performance performance = db.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = performance.Name;
            return View(performance);
        }

        //
        // GET: /Default1/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Performance performance)
        {
            if (ModelState.IsValid)
            {
                db.Performances.Add(performance);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(performance);
        }

        //
        // GET: /Default1/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            Performance performance = db.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            return View(performance);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Performance performance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(performance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(performance);
        }

        //
        // GET: /Default1/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            Performance performance = db.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            return View(performance);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Performance performance = db.Performances.Find(id);
            db.Performances.Remove(performance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Theater/MvcInternetApplication/Views/Home/AdminPanel.cshtml
@model IEnumerable<MvcInternetApplication.Models.Performance>
@{
    ViewBag.Title = @App_LocalResources.GlobalRes.ПанельАдминистратора;
}

<p>
    @Html.ActionLink(@App_LocalResources.GlobalRes.СоздатьНовуюПьесу, "Create", "Performances")
    @Html.RouteLink(@App_LocalResources.GlobalRes.ПосмотретьЗарегистрированыхПользователей, new { controller = "Account", action = "Index", area = "" })
    @Html.RouteLink(@App_LocalResources.GlobalRes.СоздатьНовыеМестаВЗале, new { controller = "Seat", action = "Create", area = "" })
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actors)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.RouteLink(@App_LocalResources.GlobalRes.Редактировать, new { controller = "Performances", action = "Edit", area = "", item.Id } )|
                @Html.RouteLink(@App_LocalResources.GlobalRes.Удалить, new { controller = "Performances", action = "Delete", area = "", item.Id }) 
            </td>
        </tr>
    }

</table>

Theater/MvcInternetApplication/Views/Home/Cabinet.cshtml
@model IEnumerable<MvcInternetApplication.Models.UserPaidShow>
@{
    ViewBag.Title = @App_LocalResources.GlobalRes.ЛичныйКабинет;
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<ul id="menu">
    @Html.ActionLink(@App_LocalResources.GlobalRes.Забронировать, "Index", "Performances")
</ul>

    @if (ViewBag.User.Count == 0)
    {
        <h3>@App_LocalResources.GlobalRes.УВасНетЗабронированыхБилетов</h3>
    }

    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Performance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment)
            </th>

            <th></th>
        </tr>
        @foreach (var item in ViewBag.User)
        {
            <tr>
                <td>
                    @item.Performance
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.SeatId
                </td>
                <td>
                    @item.Payment
                </td>
            </tr>
        }

    </table>

Theater/MvcInternetApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = @App_LocalResources.GlobalRes.Контакты;
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<section class="contact">
    <header>
        <h3>&nbsp Имя &nbsp Фамилия</h3>
    </header>
    <p>
        Кирилл Ковалев
    </p>
</section>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>Мобильный</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">kirya615@gmail.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        До востребования<br />
    </p>
</section>

Theater/MvcInternetApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = App_LocalResources.GlobalRes.Стартовая;
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
                <h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПосмотретьСписокПьес, "Index", "Performances")</h3>
            </div>
     </section>
}
<ol class="round">
    
    <p><img src="/Images/Theater.jpg" alt="Пример" width="940" height="300"></p>
    
</ol>

Theater/MvcInternetApplication/Views/Home/Сourier.cshtml
@model IEnumerable < MvcInternetApplication.Models.UserPaid >
@{
    ViewBag.Title = @App_LocalResources.GlobalRes.ДоброПожаловать;
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

@Html.RouteLink(@App_LocalResources.GlobalRes.СписокПокупателей, new{ Controller = "UserPaid",action = "Index",area = ""})